xdebug.mode = develop,debug
xdebug.start_with_request = yes
xdebug.discover_client_host = 1
xdebug.idekey = PHPSTORM



;;;;;;;;;;;; para visualização do profile é necessário a instalação do kcachegrind "sudo apt-get install -y kcachegrind"
;xdebug.mode=develop,profile
;xdebug.output_dir  = /var/www/logs
;xdebug.profiler_append = 0
;xdebug.profiler_output_name = cachegrind.out.%p
;xdebug.start_with_request = default
;xdebug.use_compression = false